### PR TITLE
Move CloudWatch to v2 of AWS SDK

### LINKED ISSUE #30: Error: no implicit conversion of LogStash::Util::Password into String
- Version: logstash-input-cloudwatch-2.1.1/logstash 6.2.4
- Operating System: Ubuntu 16.04.4 LTS
- Config File (if you have sensitive info, please remove it): 
```
cloudwatch {
    access_key_id => "XXXXXXXXXX"
    secret_access_key => "YYYYYYYYYYY"
    interval => 300
    namespace => "AWS/EC2"
    metrics => [ "CPUCreditBalance", "CPUCreditUsage", "CPUSurplusCreditBalance", "CPUSurplusCreditsCharged", "CPUUtilization", "DiskReadBytes", "DiskReadOps", "DiskWriteBytes", "DiskWriteOps", "NetworkIn", "NetworkOut", "NetworkPacketsIn", "NetworkPacketsOut", "StatusCheckFailed", "StatusCheckFailed_Instance", "StatusCheckFailed_System" ]
    region => "us-east-1"
    filters => {
        "instance-state-code" => "running"
    }
    add_field => {
        "instance-state-code" => "running"
        "techstack" => "XYZ"
        "source" => "CloudWatch"
        "region" => "us-east-1"
    }
}
```
- Sample Data: NA
- Steps to Reproduce: the same config file works fine in logstash-input-cloudwatch-2.0.3 with logstash 6.1.3. But I got this error if using logstash-input-cloudwatch-2.1.1/logstash 6.2.4

Error as follow
Error log, config file could be found if scroll down
 
```
[2018-05-04T02:22:12,493][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::CloudWatch access_key_id=>"XXXXXXXXX", secret_access_key=><password>, interval=>300, namespace=>"AWS/EC2", metrics=>["CPUCreditBalance", "CPUCreditUsage", "CPUSurplusCreditBalance", "CPUSurplusCreditsCharged", "CPUUtilization", "DiskReadBytes", "DiskReadOps", "DiskWriteBytes", "DiskWriteOps", "NetworkIn", "NetworkOut", "NetworkPacketsIn", "NetworkPacketsOut", "StatusCheckFailed", "StatusCheckFailed_Instance", "StatusCheckFailed_System"], region=>"us-east-1", filters=>{"instance-state-code"=>"running"}, add_field=>{"instance-state-code"=>"running", "techstack"=>"ZZZZZZZZ", "source"=>"CloudWatch", "region"=>"us-east-1"}, id=>"XXXXXXXXXXXXX", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"XXXXXXX", enable_metric=>true, charset=>"UTF-8">, role_session_name=>"logstash", use_ssl=>true, statistics=>["SampleCount", "Average", "Minimum", "Maximum", "Sum"], period=>300, combined=>false>
  Error: no implicit conversion of LogStash::Util::Password into String
  Exception: TypeError
  Stack: org/jruby/RubyString.java:1144:in `+'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/signers/version_4.rb:93:in `derive_key'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/signers/version_4.rb:58:in `sign_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:708:in `block in sign_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:492:in `block in client_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/response.rb:175:in `build_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/response.rb:114:in `initialize'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:203:in `new_response'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:490:in `block in client_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:391:in `log_client_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:477:in `block in client_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:373:in `return_or_raise'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `list_metrics'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-cloudwatch-2.1.1/lib/logstash/inputs/cloudwatch.rb:255:in `block in metrics_available'
org/jruby/RubyHash.java:711:in `default'
org/jruby/RubyHash.java:1100:in `[]'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-cloudwatch-2.1.1/lib/logstash/inputs/cloudwatch.rb:245:in `metrics_for'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-cloudwatch-2.1.1/lib/logstash/inputs/cloudwatch.rb:144:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-cloudwatch-2.1.1/lib/logstash/inputs/cloudwatch.rb:141:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:514:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:507:in `block in start_input'
```

### PR DESCRIPTION
**Pull request by robbavey**
Use v2 of CloudWatch API -

  enables use of more standard options from the AWS mixin
  fixes #30 (includes rudimentary IT to test correct behavior with
   password types)

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

File: spec/inputs/cloudwatch_spec.rb [hunk 1]
```diff
@@ -4,15 +4,15 @@
...
+    Aws.config[:stub_responses] = true
     Thread.abort_on_exception = true
   end
 
   describe '#register' do
     let(:config) {
       {
         'access_key_id' => '1234',
-        'secret_access_key' => 'secret',
+        'secret_access_key' => LogStash::Util::Password.new('secret'),
```
Comment (webmat) [inline spec/inputs/cloudwatch_spec.rb]: ❤️

File: lib/logstash/inputs/cloudwatch.rb [hunk 2]
```diff
@@ -230,8 +228,9 @@ def clients
     @clients ||= Hash.new do |client_hash, namespace|
       namespace = namespace[4..-1] if namespace[0..3] == 'AWS/'
       namespace = 'EC2' if namespace == 'EBS'
-      cls = AWS.const_get(namespace)
-      client_hash[namespace] = cls::Client.new(aws_options_hash)
+      cls = Aws.const_get(namespace)
+      # TODO: Move logger configuration into mixin.
```
Comment (webmat) [inline lib/logstash/inputs/cloudwatch.rb]: Forgotten TODO?

File: spec/integration/cloudwatch_spec.rb [hunk 3]
```diff
@@ -0,0 +1,26 @@
+require "logstash/devutils/rspec/spec_helper"
+require "logstash/inputs/cloudwatch"
+require "aws-sdk"
+
+describe LogStash::Inputs::CloudWatch, :integration => true do
+
+  let(:settings)  {  { "access_key_id" => ENV['AWS_ACCESS_KEY_ID'],
+                       "secret_access_key" => LogStash::Util::Password.new(ENV['AWS_SECRET_ACCESS_KEY']),
+                       "region" => ENV["AWS_REGION"] || "us-east-1",
```
Comment (webmat) [inline spec/integration/cloudwatch_spec.rb]: Perhaps raise an explicit exception with specific instructions to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` if they're nil?

File: logstash-input-cloudwatch.gemspec [hunk 4]
```diff
@@ -1,7 +1,7 @@
 Gem::Specification.new do |s|
   s.name          = 'logstash-input-cloudwatch'
-  s.version         = '2.1.1'
-  s.licenses      = ['Apache License (2.0)']
+  s.version         = '2.2.0'
+  s.licenses      = ['Apache-2.0']
```
Comment (webmat) [inline logstash-input-cloudwatch.gemspec]: ❤️

**Comment by jakelandis** [comment]
LGTM

File: lib/logstash/inputs/cloudwatch.rb (hunk 2 above)
Comment (robbavey) [reply lib/logstash/inputs/cloudwatch.rb]: This is a reminder for later - I'm planning on moving the logger config to the mixin (ideally in the integration plugin), so it will be the same across all AWS plugins

File: spec/integration/cloudwatch_spec.rb (hunk 3 above)
Comment (robbavey) [reply spec/integration/cloudwatch_spec.rb]: It is actually valid for these values to be nil - there are a [bunch of different ways](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html#plugins-inputs-s3-access_key_id) that access_keys and secret_access_keys can be set in the AWS plugins. The underlying library will raise an error if none of those methods have been set.

This test is for the specific failure when the secret_access_key was set using in the configuration, which prior to this commit would cause the plugin not to work correctly.

File: logstash-input-cloudwatch.gemspec (hunk 4 above)
Comment (robbavey) [reply logstash-input-cloudwatch.gemspec]: Yeah, I'm trying to fix these whenever I encounter them
